export { Navbar } from "./Navbar/Navbar";
export { Header } from "./Header/Header";
export { Featured } from "./Featured/Featured";
export { PropertyList } from "./PropertyList/PropertyList";
export { FeaturedProperties } from "./FeaturedProperties/FeaturedProperties";
export { MailList } from "./MailList/MailList";
export { Footer } from "./Footer/Footer";
export { HotelCard } from "./HotelCard/HotelCard";
export { HotelsSearch } from "./HotelsSearch/HotelsSearch";
